// Generated by https://quicktype.io

export interface OnGivenDate {
    date: string;
    url:  string;
    data: Data;
}

export interface Data {
    Events: Details[];
    Births: Details[];
    Deaths: Details[];
}

export interface Details {
    year:         string;
    text:         string;
    html:         string;
    no_year_html: string;
    links:        Link[];
}

export interface Link {
    title: string;
    link:  string;
}
