// Generated by https://quicktype.io from data at http://history.muffinlabs.com/date

export interface TodayMuffinLabs {
    date: string;
    url:  string;
    data: Data;
}

/* The are the key-value pairs of the object called data in interface Today.
That is why Data is capitalised above. */
export interface Data {
    Events: Details[];
    Births: Details[];
    Deaths: Details[];
}

export interface Details {
    year:         string;
    text:         string;
    html:         string;
    no_year_html: string;
    links:        Link[];
}

export interface Link {
    title: string;
    link:  string;
}
