// Generated by https://quicktype.io

export interface OnGivenDateWikipedia {
    selected: Event[];
    births: Event[];
    deaths: Event[];
    events: Event[];
    holidays: Holiday[];
}

export interface Event {
    text: string;
    pages: Page[];
    year: number;
}

export interface Holiday {
    text: string;
    pages: Page[];
}

export interface Page {
    type: string;
    title: string;
    displaytitle: string;
    namespace: Namespace;
    wikibase_item: string;
    titles: Titles;
    pageid: number;
    thumbnail?: Originalimage;
    originalimage?: Originalimage;
    lang: string;
    dir: string;
    revision: string;
    tid: string;
    timestamp: Date;
    description?: string;
    description_source?: string;
    content_urls: ContentUrls;
    extract: string;
    extract_html: string;
    normalizedtitle: string;
    coordinates?: Coordinates;
}

export interface Namespace {
    id: number;
    text: string;
}

export interface Titles {
    canonical: string;
    normalized: string;
    display: string;
}

export interface Originalimage {
    source: string;
    width: number;
    height: number;
}

export interface ContentUrls {
    desktop: Desktop;
    mobile: Desktop;
}

export interface Coordinates {
    lat: number;
    lon: number;
}

export interface Desktop {
    page: string;
    revisions: string;
    edit: string;
    talk: string;
}

/* "In TypeScript 5.8, a new flag is dropping. It's called erasableSyntaxOnly.
It disables a bunch of features that I don't think should ever have been part of TypeScript. (...)
erasableSyntaxOnly marks enums, namespaces and class parameter properties as errors. These pieces of syntax are not considered erasable."
https://www.totaltypescript.com/erasable-syntax-only 

"The Typescript team itself has seen value in this and has shipped a new --erasable-syntax-only flag, that disallows certain Typescript features that are not compatible with such a transformation. Fortunately, none of these incompatible features are all that important to begin with and are usually just syntax conveniences that helps write less code. There is one exception, however, enums."
https://nmn.sh/blog/2025-03-09-new-enum-syntax

This seems to mean that the value that goes with the corresponding property (type, lang, etc.) is always the same.
It's a string. That's all I need to know.
export enum Type {
    Standard = "standard",
}
export enum Lang {
    En = "en",
}
export enum Dir {
    LTR = "ltr",
}
export enum DescriptionSource {
    Local = "local",
}
*/

